### ISSUE TITLE
Inconsistent naming breaks links in README.adoc

### ISSUE THREAD

**Issue by PascalSchwarz** [barclay-reg/dhbw-slides#8]
Hi,
the VCS 4 links are all 404 due to the fact that the 08-vcs-4.adoc is differing from the naming convention:
04-vcs2.adoc
06-vcs3.adoc
08-vcs-4.adoc

I think PR #7 should fix this, aswell as some spelling mistakes.
Cheers

**Comment by antoniaroedel** [comment]
reproducible
